import RootLayout from '@components/Layout/RootLayout';
import localFont from 'next/font/local';
import Head from 'next/head';

const myFont = localFont({
  src: '../../public/fonts/MerriweatherSans.ttf',
  variable: '--font-myfont',
});
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <div>
        <h1>
          Hello this is next js Lorem ipsum dolor sit amet consectetur
          adipisicing elit. Qui ab delectus assumenda dicta ratione
          recusandae harum voluptate error eos ipsum, et sequi
          eligendi, ipsa aut cupiditate rem! Possimus, qui accusamus.
        </h1>
      </div>
    </>
  );
}

Home.getLayout = (Page) => {
  return <RootLayout>{Page}</RootLayout>;
};
