import RootLayout from '@components/Layout/RootLayout';
import Landing from '@components/UI/Landing';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Landing />
    </>
  );
}

Home.getLayout = (Page) => {
  return <RootLayout>{Page}</RootLayout>;
};
